### ISSUE TITLE
求解答

### ISSUE THREAD

**Issue by swqtc** [yonetaniryo/DPHE-demo#1]
如果非零元素特别多，这方法是不是就和普通方法一样？效率差别不太大。误差是不是也会变得特别大

**Comment by yonetaniryo** [comment]
"If there are many non-zero elements, is this method the same as the normal method? The efficiency difference is not too great. Does the error also become particularly large?"

Is this what you are asking?
Yes. this method works effectively only when input data are sparse -- i.e., having many zero elements, and otherwise works as the standard HE. Nevertheless, the number of non-zero elements does not cause any error in encryption.
